name: Trigger auto deployment for container-app-s6gvgxykojh6w

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-s6gvgxykojh6w-AutoDeployTrigger-14429f67-9be6-4f66-a89e-3e086a230084.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPS6GVGXYKOJH6W_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPS6GVGXYKOJH6W_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPS6GVGXYKOJH6W_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrys6gvgxykojh6w.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPS6GVGXYKOJH6W_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPS6GVGXYKOJH6W_REGISTRY_PASSWORD }}
          containerAppName: container-app-s6gvgxykojh6w
          resourceGroup: expresssample9f379dc2
          imageToBuild: containerregistrys6gvgxykojh6w.azurecr.io/container-app-s6gvgxykojh6w:${{ github.sha }}
          


